"""Actual KOSPI200 / KOSDAQ150 membership, rather than a ranking that resembles it.

``data/kr_index_members.json`` is generated by
``scripts/build_kr_index_members.py`` from the constituents of the index ETFs
(KODEX 200 and KODEX 코스닥150) as NH reports them. An index ETF has to hold
the index, so its holdings are the index — which is the cheapest correct answer
available without a KRX data-portal account.

It is checked in rather than fetched at run time for three reasons: the
screener runs on hosts with no NH credentials, membership changes quarterly so
a stale file is nearly always right, and a change in membership shows up in a
diff instead of silently moving what the screener looked at.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

MEMBERS_PATH = Path(__file__).resolve().parent / "data" / "kr_index_members.json"

# The ETF that tracks each index, and therefore holds it.
INDEX_ETFS = {
    "KOSPI200": ("069500", "KODEX 200"),
    "KOSDAQ150": ("229200", "KODEX 코스닥150"),
}

# A constituent list that has lost most of its names is worse than no list at
# all: it would quietly shrink the universe instead of failing. Below this the
# file is treated as unusable.
MIN_PLAUSIBLE = {"KOSPI200": 150, "KOSDAQ150": 100}


@dataclass(frozen=True)
class IndexMembers:
    index: str
    codes: tuple[str, ...]
    names: dict[str, str]
    as_of: str
    source: str

    def __len__(self) -> int:
        return len(self.codes)


def _load_file(path: str | None = None) -> dict:
    # An override exists so a test, or someone keeping their own list, can point
    # at a different file without editing the shipped one. The cache is keyed on
    # the resolved path rather than the argument, so changing the environment
    # variable picks a different entry instead of reusing a stale one.
    return _read(str(path or os.getenv("TRADINGAGENTS_INDEX_MEMBERS_PATH") or MEMBERS_PATH))


@lru_cache(maxsize=8)
def _read(target: str) -> dict:
    path = Path(target)
    if not path.exists():
        return {}
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    return raw if isinstance(raw, dict) else {}


def load_index_members(index: str, *, path: str | None = None) -> IndexMembers | None:
    """The stored membership for one index, or None when it is missing or too short."""

    name = str(index).strip().upper()
    stored = (_load_file(path).get("indices") or {}).get(name)
    if not isinstance(stored, dict):
        return None

    members = [row for row in (stored.get("members") or []) if isinstance(row, dict)]
    codes = tuple(str(row.get("code") or "").strip() for row in members)
    codes = tuple(code for code in codes if code)
    if len(codes) < MIN_PLAUSIBLE.get(name, 1):
        return None

    return IndexMembers(
        index=name,
        codes=codes,
        names={str(row.get("code") or ""): str(row.get("name") or "") for row in members},
        as_of=str(stored.get("as_of") or ""),
        source=str(stored.get("source") or ""),
    )


def index_member_codes(index: str, *, path: str | None = None) -> list[str]:
    """Just the codes, empty when the file cannot be used."""

    members = load_index_members(index, path=path)
    return list(members.codes) if members else []


def is_tradeable_code(code: str) -> bool:
    """Six characters KRX will accept as a ticker.

    Not all of them are digits. Newly listed and spun-off shares carry codes
    like 0126Z0, and dropping those would quietly lose real constituents.
    """

    text = str(code or "").strip()
    return len(text) == 6 and text.isalnum()
