"""Full KOSPI/KOSDAQ ticker directory for offline name search.

``data/kr_tickers.json`` (``[{"code", "name", "market"}, ...]``) is generated by
``scripts/build_kr_ticker_directory.py`` (GitHub Actions, weekly) from the Naver
market-cap listing, so member forms can resolve any listed name without a live
vendor call. Search ranks exact code, code prefix, name prefix, then substring.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Iterable

DIRECTORY_PATH = Path(__file__).resolve().parent / "data" / "kr_tickers.json"
_SPACES = re.compile(r"\s+")


@dataclass(frozen=True)
class DirectoryEntry:
    code: str
    name: str
    market: str
    sector: str = ""
    rank: int = 0


def _fold(text: str) -> str:
    return _SPACES.sub("", str(text or "")).casefold()


@lru_cache(maxsize=1)
def load_directory(path: str | None = None) -> tuple[DirectoryEntry, ...]:
    target = Path(path) if path else DIRECTORY_PATH
    if not target.exists():
        return ()
    try:
        raw = json.loads(target.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return ()
    rows = raw.get("items") if isinstance(raw, dict) else raw
    entries: list[DirectoryEntry] = []
    seen: set[str] = set()
    for row in rows or ():
        code = str(row.get("code") or "").strip()
        name = str(row.get("name") or "").strip()
        market = str(row.get("market") or "").strip().upper() or "UNKNOWN"
        if len(code) != 6 or not code.isdigit() or not name or code in seen:
            continue
        seen.add(code)
        try:
            rank = int(row.get("rank") or 0)
        except (TypeError, ValueError):
            rank = 0
        entries.append(DirectoryEntry(code=code, name=name, market=market, sector=str(row.get("sector") or "").strip(), rank=rank))
    return tuple(entries)


def top_by_market_cap(limit: int = 200, markets: tuple[str, ...] = ("KOSPI", "KOSDAQ")) -> list[DirectoryEntry]:
    """The largest listings first, without a live vendor call.

    The directory is rebuilt weekly from Naver's market-cap ranking, so each row
    already knows where it stood. A backtest that picks its universe from here
    is reproducible and does not depend on a vendor answering right now.
    """

    wanted = {market.upper() for market in markets}
    ranked = [
        entry
        for entry in load_directory()
        if entry.rank and entry.market.upper() in wanted and "ETF" not in entry.name.upper()
    ]
    ranked.sort(key=lambda entry: entry.rank)
    return ranked[: max(limit, 1)]


def sector_of(code: str) -> str:
    """Industry group for a ticker, or "" when the directory has not been rebuilt."""

    entry = lookup_directory(code)
    return getattr(entry, "sector", "") if entry else ""


def directory_size() -> int:
    return len(load_directory())


def lookup_directory(code: str) -> DirectoryEntry | None:
    code = str(code or "").strip()
    for entry in load_directory():
        if entry.code == code:
            return entry
    return None


def search_directory(query: str, *, limit: int = 10) -> list[DirectoryEntry]:
    """Rank: exact code, code prefix, name prefix, name substring; stable by name."""

    needle = _fold(query)
    if not needle:
        return []
    exact: list[DirectoryEntry] = []
    code_prefix: list[DirectoryEntry] = []
    name_prefix: list[DirectoryEntry] = []
    contains: list[DirectoryEntry] = []
    for entry in load_directory():
        folded = _fold(entry.name)
        if entry.code == needle:
            exact.append(entry)
        elif needle.isdigit() and entry.code.startswith(needle):
            code_prefix.append(entry)
        elif folded.startswith(needle):
            name_prefix.append(entry)
        elif needle in folded:
            contains.append(entry)
    ranked: list[DirectoryEntry] = []
    for bucket in (exact, code_prefix, sorted(name_prefix, key=lambda e: (len(e.name), e.name)), sorted(contains, key=lambda e: (len(e.name), e.name))):
        for entry in bucket:
            if len(ranked) >= limit:
                return ranked
            ranked.append(entry)
    return ranked


def write_directory(entries: Iterable[DirectoryEntry | dict], path: Path | None = None, *, source: str = "naver") -> Path:
    target = path or DIRECTORY_PATH
    items = []
    seen: set[str] = set()
    for entry in entries:
        if isinstance(entry, DirectoryEntry):
            code, name, market, sector, rank = entry.code, entry.name, entry.market, entry.sector, entry.rank
        else:
            code, name, market = str(entry.get("code")), str(entry.get("name")), str(entry.get("market"))
            sector = str(entry.get("sector") or "")
            rank = int(entry.get("rank") or 0)
        if code in seen:
            continue
        seen.add(code)
        row = {"code": code, "name": name, "market": market}
        if sector:
            row["sector"] = sector
        if rank:
            row["rank"] = rank
        items.append(row)
    items.sort(key=lambda item: item["code"])
    from datetime import date

    payload = {"generated_on": date.today().isoformat(), "source": source, "count": len(items), "items": items}
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + "\n", encoding="utf-8")
    load_directory.cache_clear()
    return target
