"""SQLAlchemy table definitions for TradingAgents storage."""

from __future__ import annotations

from sqlalchemy import (
    Boolean,
    Column,
    JSON,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    MetaData,
    Numeric,
    String,
    Table,
    Text,
    UniqueConstraint,
    Uuid,
    func,
)


metadata = MetaData()

analysis_runs = Table(
    "analysis_runs",
    metadata,
    Column("id", Uuid(as_uuid=False), primary_key=True),
    Column("user_id", Uuid(as_uuid=False), nullable=True),
    Column("ticker_code", String(12), nullable=False, index=True),
    Column("ticker_name", String(120), nullable=True),
    Column("market", String(32), nullable=False, default="KR"),
    Column("trade_date", Date, nullable=False, index=True),
    Column("status", String(32), nullable=False, default="pending"),
    Column("visibility", String(16), nullable=False, default="public"),
    Column("model_provider", String(64), nullable=True),
    Column("deep_model", String(128), nullable=True),
    Column("quick_model", String(128), nullable=True),
    Column("metadata_json", JSON, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("completed_at", DateTime(timezone=True), nullable=True),
)

agent_reports = Table(
    "agent_reports",
    metadata,
    Column("id", Uuid(as_uuid=False), primary_key=True),
    Column("analysis_run_id", Uuid(as_uuid=False), ForeignKey("analysis_runs.id", ondelete="CASCADE"), nullable=False),
    Column("role", String(64), nullable=False),
    Column("title", String(160), nullable=True),
    Column("content", Text, nullable=False),
    Column("metadata_json", JSON, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint("analysis_run_id", "role", name="uq_agent_reports_run_role"),
)

trade_decisions = Table(
    "trade_decisions",
    metadata,
    Column("id", Uuid(as_uuid=False), primary_key=True),
    Column("analysis_run_id", Uuid(as_uuid=False), ForeignKey("analysis_runs.id", ondelete="CASCADE"), nullable=False),
    Column("rating", String(64), nullable=False),
    Column("action", String(64), nullable=False),
    Column("target_weight", Float, nullable=True),
    Column("rationale", Text, nullable=False, default=""),
    Column("raw_decision", Text, nullable=False, default=""),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint("analysis_run_id", name="uq_trade_decisions_run"),
)

analysis_outcomes = Table(
    "analysis_outcomes",
    metadata,
    Column("id", Uuid(as_uuid=False), primary_key=True),
    Column("analysis_run_id", Uuid(as_uuid=False), ForeignKey("analysis_runs.id", ondelete="CASCADE"), nullable=False),
    Column("ticker_code", String(12), nullable=False, index=True),
    Column("ticker_name", String(120), nullable=True),
    Column("market", String(32), nullable=False, default="KR"),
    Column("trade_date", Date, nullable=False, index=True),
    Column("evaluated_at", Date, nullable=False),
    Column("horizon_days", Integer, nullable=False),
    Column("actual_holding_days", Integer, nullable=True),
    Column("entry_close", Numeric(18, 4), nullable=True),
    Column("exit_close", Numeric(18, 4), nullable=True),
    Column("benchmark_symbol", String(32), nullable=True),
    Column("benchmark_entry_close", Numeric(18, 4), nullable=True),
    Column("benchmark_exit_close", Numeric(18, 4), nullable=True),
    Column("raw_return", Float, nullable=True),
    Column("benchmark_return", Float, nullable=True),
    Column("alpha_return", Float, nullable=True),
    Column("decision_rating", String(64), nullable=True),
    Column("decision_action", String(64), nullable=True),
    Column("status", String(32), nullable=False, default="pending"),
    Column("error", Text, nullable=True),
    Column("metadata_json", JSON, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint("analysis_run_id", "horizon_days", name="uq_analysis_outcomes_run_horizon"),
)

analysis_refresh_requests = Table(
    "analysis_refresh_requests",
    metadata,
    Column("id", Uuid(as_uuid=False), primary_key=True),
    Column("user_id", Uuid(as_uuid=False), nullable=True, index=True),
    Column("ticker_code", String(12), nullable=False, index=True),
    Column("ticker_name", String(120), nullable=True),
    Column("market", String(32), nullable=False, default="KR"),
    Column("requested_trade_date", Date, nullable=False, index=True),
    Column("status", String(32), nullable=False, default="queued"),
    Column("analysis_run_id", Uuid(as_uuid=False), ForeignKey("analysis_runs.id", ondelete="SET NULL"), nullable=True),
    Column("reason", Text, nullable=True),
    Column("metadata_json", JSON, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
)

manual_portfolios = Table(
    "manual_portfolios",
    metadata,
    Column("id", Uuid(as_uuid=False), primary_key=True),
    Column("user_id", Uuid(as_uuid=False), nullable=False, index=True),
    Column("name", String(120), nullable=False),
    Column("base_currency", String(8), nullable=False, default="KRW"),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
)

manual_trades = Table(
    "manual_trades",
    metadata,
    Column("id", Uuid(as_uuid=False), primary_key=True),
    Column("portfolio_id", Uuid(as_uuid=False), ForeignKey("manual_portfolios.id", ondelete="CASCADE"), nullable=False),
    Column("ticker_code", String(12), nullable=False, index=True),
    Column("ticker_name", String(120), nullable=True),
    Column("market", String(32), nullable=False, default="KR"),
    Column("side", String(8), nullable=False),
    Column("trade_date", Date, nullable=False, index=True),
    Column("price", Numeric(18, 4), nullable=False),
    Column("quantity", Integer, nullable=False),
    Column("fee", Numeric(18, 4), nullable=False, default=0),
    Column("tax", Numeric(18, 4), nullable=False, default=0),
    Column("memo", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
)

manual_price_targets = Table(
    "manual_price_targets",
    metadata,
    Column("id", Uuid(as_uuid=False), primary_key=True),
    Column("portfolio_id", Uuid(as_uuid=False), ForeignKey("manual_portfolios.id", ondelete="CASCADE"), nullable=False),
    Column("ticker_code", String(12), nullable=False, index=True),
    Column("target_price", Numeric(18, 4), nullable=True),
    Column("stop_price", Numeric(18, 4), nullable=True),
    Column("memo", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint("portfolio_id", "ticker_code", name="uq_manual_price_targets_portfolio_ticker"),
)

manual_watchlists = Table(
    "manual_watchlists",
    metadata,
    Column("id", Uuid(as_uuid=False), primary_key=True),
    Column("user_id", Uuid(as_uuid=False), nullable=False, index=True),
    Column("name", String(120), nullable=False),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
)

manual_watchlist_items = Table(
    "manual_watchlist_items",
    metadata,
    Column("id", Uuid(as_uuid=False), primary_key=True),
    Column("watchlist_id", Uuid(as_uuid=False), ForeignKey("manual_watchlists.id", ondelete="CASCADE"), nullable=False),
    Column("ticker_code", String(12), nullable=False, index=True),
    Column("ticker_name", String(120), nullable=True),
    Column("market", String(32), nullable=False, default="KR"),
    Column("memo", Text, nullable=True),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint("watchlist_id", "ticker_code", name="uq_manual_watchlist_items_watchlist_ticker"),
)

paper_simulation_accounts = Table(
    "paper_simulation_accounts",
    metadata,
    Column("id", Uuid(as_uuid=False), primary_key=True),
    Column("user_id", Uuid(as_uuid=False), nullable=False, index=True),
    Column("name", Text, nullable=False, default="AI 가상매매"),
    Column("base_currency", String(8), nullable=False, default="KRW"),
    Column("initial_cash", Numeric(18, 4), nullable=False, default=10000000),
    Column("cash_balance", Numeric(18, 4), nullable=False, default=10000000),
    Column("status", String(24), nullable=False, default="active"),
    Column("metadata_json", JSON, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint("user_id", "name", name="uq_paper_simulation_accounts_user_name"),
)

paper_simulation_positions = Table(
    "paper_simulation_positions",
    metadata,
    Column("id", Uuid(as_uuid=False), primary_key=True),
    Column("account_id", Uuid(as_uuid=False), ForeignKey("paper_simulation_accounts.id", ondelete="CASCADE"), nullable=False),
    Column("user_id", Uuid(as_uuid=False), nullable=False, index=True),
    Column("analysis_run_id", Uuid(as_uuid=False), ForeignKey("analysis_runs.id", ondelete="SET NULL"), nullable=True),
    Column("analysis_request_id", Uuid(as_uuid=False), ForeignKey("analysis_refresh_requests.id", ondelete="SET NULL"), nullable=True),
    Column("ticker_code", String(12), nullable=False, index=True),
    Column("ticker_name", String(120), nullable=True),
    Column("market", String(32), nullable=False, default="KR"),
    Column("status", String(24), nullable=False, default="open"),
    Column("quantity", Integer, nullable=False, default=0),
    Column("entry_date", Date, nullable=True),
    Column("entry_price", Numeric(18, 4), nullable=True),
    Column("average_price", Numeric(18, 4), nullable=True),
    Column("target_price", Numeric(18, 4), nullable=True),
    Column("stop_price", Numeric(18, 4), nullable=True),
    Column("exit_date", Date, nullable=True),
    Column("exit_price", Numeric(18, 4), nullable=True),
    Column("exit_reason", Text, nullable=True),
    Column("realized_pnl", Numeric(18, 4), nullable=True),
    Column("realized_return", Float, nullable=True),
    Column("decision_rating", String(64), nullable=True),
    Column("decision_action", String(64), nullable=True),
    Column("target_weight", Float, nullable=True),
    Column("metadata_json", JSON, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
)

harness_runs = Table(
    "harness_runs",
    metadata,
    Column("id", Uuid(as_uuid=False), primary_key=True),
    Column("as_of_date", Date, nullable=False, index=True),
    Column("mode", String(16), nullable=False, default="paper"),
    Column("broker", String(32), nullable=False, default="paper"),
    Column("dry_run", Integer, nullable=False, default=1),
    Column("confirmer", String(32), nullable=False, default="none"),
    Column("visibility", String(16), nullable=False, default="public"),
    Column("status", String(32), nullable=False, default="completed"),
    Column("markets", String(64), nullable=False, default="KOSPI,KOSDAQ"),
    Column("universe_size", Integer, nullable=False, default=0),
    Column("candidate_count", Integer, nullable=False, default=0),
    Column("order_count", Integer, nullable=False, default=0),
    Column("cash_before", Numeric(18, 4), nullable=True),
    Column("cash_after", Numeric(18, 4), nullable=True),
    Column("audit_sequence_start", Integer, nullable=True),
    Column("audit_sequence_end", Integer, nullable=True),
    Column("notes_json", JSON, nullable=False, default=list),
    Column("metadata_json", JSON, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
)

harness_decisions = Table(
    "harness_decisions",
    metadata,
    Column("id", Uuid(as_uuid=False), primary_key=True),
    Column("harness_run_id", Uuid(as_uuid=False), ForeignKey("harness_runs.id", ondelete="CASCADE"), nullable=False, index=True),
    Column("as_of_date", Date, nullable=False, index=True),
    Column("ticker_code", String(12), nullable=False, index=True),
    Column("ticker_name", String(120), nullable=True),
    Column("market", String(32), nullable=False, default="KR"),
    Column("stage", String(32), nullable=False),
    Column("screener_rank", Integer, nullable=True),
    Column("composite_score", Float, nullable=True),
    Column("forecast_expected_return", Float, nullable=True),
    Column("forecast_probability_up", Float, nullable=True),
    Column("confirmation_rating", String(32), nullable=True),
    Column("confirmation_confidence", Float, nullable=True),
    Column("confirmation_source", String(32), nullable=True),
    Column("quantity", Integer, nullable=True),
    Column("entry_price", Numeric(18, 4), nullable=True),
    Column("stop_price", Numeric(18, 4), nullable=True),
    Column("take_profit_price", Numeric(18, 4), nullable=True),
    Column("order_status", String(32), nullable=True),
    Column("reasons_json", JSON, nullable=False, default=list),
    Column("detail_json", JSON, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
)

subscriptions = Table(
    "subscriptions",
    metadata,
    Column("id", Uuid(as_uuid=False), primary_key=True),
    Column("user_id", Uuid(as_uuid=False), nullable=False, unique=True),
    Column("plan", String(16), nullable=False, default="free"),
    Column("status", String(24), nullable=False, default="inactive"),
    Column("provider", String(24), nullable=False, default="portone"),
    Column("customer_key", String(120), nullable=True),
    Column("billing_key", String(200), nullable=True),
    Column("trial_ends_at", DateTime(timezone=True), nullable=True),
    Column("current_period_start", DateTime(timezone=True), nullable=True),
    Column("current_period_end", DateTime(timezone=True), nullable=True),
    Column("cancel_at_period_end", Boolean, nullable=False, default=False),
    Column("last_payment_id", String(120), nullable=True),
    Column("last_payment_at", DateTime(timezone=True), nullable=True),
    Column("failure_count", Integer, nullable=False, default=0),
    Column("metadata_json", JSON, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
)

billing_events = Table(
    "billing_events",
    metadata,
    Column("id", Uuid(as_uuid=False), primary_key=True),
    Column("subscription_id", Uuid(as_uuid=False), ForeignKey("subscriptions.id", ondelete="SET NULL"), nullable=True),
    Column("user_id", Uuid(as_uuid=False), nullable=True, index=True),
    Column("provider", String(24), nullable=False, default="portone"),
    Column("event_type", String(64), nullable=False),
    Column("payment_id", String(120), nullable=True, index=True),
    Column("amount", Numeric(18, 2), nullable=True),
    Column("currency", String(8), nullable=False, default="KRW"),
    Column("status", String(24), nullable=True),
    Column("message", Text, nullable=True),
    Column("payload_json", JSON, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
)

notification_channels = Table(
    "notification_channels",
    metadata,
    Column("id", Uuid(as_uuid=False), primary_key=True),
    Column("user_id", Uuid(as_uuid=False), nullable=False, index=True),
    Column("channel", String(24), nullable=False, default="telegram"),
    Column("external_id", String(120), nullable=True, index=True),
    Column("display_name", String(120), nullable=True),
    Column("link_code", String(32), nullable=True, index=True),
    Column("link_code_expires_at", DateTime(timezone=True), nullable=True),
    Column("linked_at", DateTime(timezone=True), nullable=True),
    Column("enabled", Boolean, nullable=False, default=True),
    Column("metadata_json", JSON, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint("user_id", "channel", name="uq_notification_channels_user_channel"),
)

harness_outcomes = Table(
    "harness_outcomes",
    metadata,
    Column("id", Uuid(as_uuid=False), primary_key=True),
    Column("harness_decision_id", Uuid(as_uuid=False), ForeignKey("harness_decisions.id", ondelete="CASCADE"), nullable=False, index=True),
    Column("harness_run_id", Uuid(as_uuid=False), ForeignKey("harness_runs.id", ondelete="CASCADE"), nullable=False, index=True),
    Column("ticker_code", String(12), nullable=False, index=True),
    Column("ticker_name", String(120), nullable=True),
    Column("market", String(32), nullable=False, default="KR"),
    Column("entry_date", Date, nullable=False, index=True),
    Column("evaluated_at", Date, nullable=False),
    Column("horizon_days", Integer, nullable=False),
    Column("actual_holding_days", Integer, nullable=True),
    Column("benchmark_symbol", String(32), nullable=True),
    Column("raw_return", Float, nullable=True),
    Column("benchmark_return", Float, nullable=True),
    Column("alpha_return", Float, nullable=True),
    Column("confirmation_rating", String(32), nullable=True),
    Column("confirmation_source", String(32), nullable=True),
    Column("status", String(32), nullable=False, default="pending"),
    Column("error", Text, nullable=True),
    Column("metadata_json", JSON, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    Column("updated_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
    UniqueConstraint("harness_decision_id", "horizon_days", name="uq_harness_outcomes_decision_horizon"),
)

paper_simulation_events = Table(
    "paper_simulation_events",
    metadata,
    Column("id", Uuid(as_uuid=False), primary_key=True),
    Column("account_id", Uuid(as_uuid=False), ForeignKey("paper_simulation_accounts.id", ondelete="CASCADE"), nullable=False),
    Column("position_id", Uuid(as_uuid=False), ForeignKey("paper_simulation_positions.id", ondelete="CASCADE"), nullable=True),
    Column("user_id", Uuid(as_uuid=False), nullable=False, index=True),
    Column("analysis_run_id", Uuid(as_uuid=False), ForeignKey("analysis_runs.id", ondelete="SET NULL"), nullable=True),
    Column("event_type", String(32), nullable=False),
    Column("side", String(8), nullable=True),
    Column("event_date", Date, nullable=False, index=True),
    Column("ticker_code", String(12), nullable=False, index=True),
    Column("price", Numeric(18, 4), nullable=True),
    Column("quantity", Integer, nullable=True),
    Column("notional", Numeric(18, 4), nullable=True),
    Column("commission", Numeric(18, 4), nullable=False, default=0),
    Column("transaction_tax", Numeric(18, 4), nullable=False, default=0),
    Column("reason", Text, nullable=True),
    Column("metadata_json", JSON, nullable=False, default=dict),
    Column("created_at", DateTime(timezone=True), nullable=False, server_default=func.now()),
)
